# https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller

repositories:
  - name: actions-runner-controller-charts
    url: ghcr.io/actions/actions-runner-controller-charts
    oci: true

releases:
  - name: arc
    namespace: arc-systems
    chart: actions-runner-controller-charts/gha-runner-scale-set-controller
    version: 0.4.0

  - name: arc-runner-set
    namespace: arc-runners
    chart: actions-runner-controller-charts/gha-runner-scale-set
    version: 0.4.0
    needs:
      - arc-systems/arc
    values:
      - githubConfigUrl: https://github.com/{{ requiredEnv "GITHUB_REPOSITORY" }}
        githubConfigSecret:
          github_app_id: {{ requiredEnv "APP_ID" | quote }}
          github_app_installation_id: {{ requiredEnv "APP_INSTALLATION_ID" | quote }}
          github_app_private_key: {{ requiredEnv "APP_PRIVATE_KEY" | quote }}
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/int128/actions-runner:2.304.0
                command: ["/home/runner/run.sh"]

helmDefaults:
  wait: true
