# https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller

repositories:
  - name: actions-runner-controller-charts
    url: ghcr.io/actions/actions-runner-controller-charts
    oci: true

releases:
  - name: arc
    namespace: arc-systems
    chart: actions-runner-controller-charts/gha-runner-scale-set-controller
    version: 0.8.0

  - needs: [arc-systems/arc]
    name: runner-scale-set-{{ requiredEnv "GITHUB_RUN_ID" }}
    namespace: arc-runners
    chart: actions-runner-controller-charts/gha-runner-scale-set
    version: 0.8.0
    values:
      - githubConfigUrl: https://github.com/{{ requiredEnv "GITHUB_REPOSITORY" }}
        githubConfigSecret:
          github_app_id: {{ requiredEnv "APP_ID" | quote }}
          github_app_installation_id: {{ requiredEnv "APP_INSTALLATION_ID" | quote }}
          github_app_private_key: {{ requiredEnv "APP_PRIVATE_KEY" | quote }}

helmDefaults:
  wait: true
