repositories:
  # https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller
  - name: actions-runner-controller-charts
    url: ghcr.io/actions/actions-runner-controller-charts
    oci: true

releases:
  - name: arc
    namespace: arc-systems
    chart: actions-runner-controller-charts/gha-runner-scale-set-controller
    version: 0.4.0

  - name: arc-runner-set
    namespace: arc-runners
    chart: actions-runner-controller-charts/gha-runner-scale-set
    version: 0.4.0
    needs:
      - arc
    values:
      - githubConfigUrl: https://github.com/{{ requiredEnv "GITHUB_REPOSITORY" }}
        githubConfigSecret:
          github_token: {{ requiredEnv "GITHUB_TOKEN" }}
